version: '3.1'
services:
  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - docker.env

  init_db:
    depends_on:
      - db
    build: .
    command: bash -c "python3 src/00-dataset_to_db.py"
    env_file:
      - docker.env
    links:
      - "db:database"
